Repository hochschule-darmstadt-UAS/ddk-artbrowser, pull requests merged in 2020-12, with the labels that each got.

#33 7/modify material component to match new data model
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/iconography/iconography.component.scss
  app/src/app/pages/material/material.component.html
  app/src/app/shared/components/information/information.component.html
  app/src/app/shared/components/information/information.component.scss
  app/src/app/shared/components/information/information.component.ts
  app/src/app/shared/components/title/title.component.html
  app/src/app/shared/components/title/title.component.scss
  app/src/app/shared/models/entity.interface.ts
Labels: frontend, high priority

#37 5/artwork modifications
  .pre-commit-config.yaml
  app/package.json
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.spec.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/artwork/artwork.routing.module.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/genre/genre.component.spec.ts
  app/src/app/pages/home/home.component.spec.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/location/location.component.spec.ts
  app/src/app/pages/material/material.component.spec.ts
  app/src/app/pages/type/type.component.spec.ts
  app/src/app/shared/components/abstract/abstract.component.html
  app/src/app/shared/components/abstract/abstract.component.scss
  app/src/app/shared/components/abstract/abstract.component.spec.ts
  app/src/app/shared/components/abstract/abstract.component.ts
  app/src/app/shared/components/badge/badge.component.ts
  app/src/app/shared/components/dimensions/dimensions.component.ts
  app/src/app/shared/components/timeline/timeline.component.html
  app/src/app/shared/components/timeline/timeline.component.scss
  app/src/app/shared/components/timeline/timeline.component.spec.ts
  app/src/app/shared/components/timeline/timeline.component.ts
  app/src/app/shared/components/title/title.component.html
  app/src/app/shared/models/entity.interface.ts
  app/src/app/shared/models/utils.ts
  app/src/app/shared/shared.module.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  app/src/locale/messages.xlf
Labels: frontend

#35 8/modify genre component to match new data model
  app/src/app/pages/genre/genre.component.html
  app/src/locale/messages.de.xlf
Labels: frontend

#36 6/modify artist component to match new data model
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/material/material.component.html
  app/src/locale/messages.de.xlf
Labels: frontend

#41 #39: mostly renamed .type to .entityType. changed Type Icon
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/core/services/iconclass/iconclass.service.ts
  app/src/app/core/services/search.service.ts
  app/src/app/pages/home/home.component.ts
  app/src/app/pages/search-result/search-result.component.ts
  app/src/app/shared/components/dimensions/dimensions.component.ts
  app/src/app/shared/components/infinite-scroll/infinite-scroll.component.ts
  app/src/app/shared/components/search/search.component.html
  app/src/app/shared/components/search/search.component.ts
  app/src/app/shared/models/entity.interface.ts
Labels: frontend, medium priority

#44 Fix entity image
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/search-result/search-result.component.ts
  app/src/app/shared/components/badge/badge.component.ts
  app/src/app/shared/models/artwork.interface.ts
  app/src/app/shared/models/entity.interface.ts
  app/src/locale/messages.xlf
  etl/data_samples/artwork.json
  etl/data_samples/location.json
Labels: frontend

#45 #17: reordered elements on home page and fixed some css
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/home/home.component.html
  app/src/app/pages/home/home.component.scss
Labels: frontend, low priority

#46 9/modify location component to match new data model
  app/src/app/pages/home/home.component.html
  app/src/app/pages/home/home.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/material/material.component.html
  app/src/app/shared/components/information/information.component.html
  app/src/app/shared/components/information/information.component.ts
  app/src/app/shared/models/location.interface.ts
  app/src/app/shared/models/utils.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
Labels: frontend, medium priority

#47 42: fix timeline component for arbitrary date formats, introduced ddk…
  app/src/app/core/services/ddk.service.ts
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/shared/components/information/information.component.ts
  app/src/app/shared/components/timeline/timeline.component.html
  app/src/app/shared/components/timeline/timeline.component.spec.ts
  app/src/app/shared/components/timeline/timeline.component.ts
  app/src/app/shared/models/artwork.interface.ts
  app/src/app/shared/models/entity.interface.ts
  app/src/app/shared/models/inlineInterfaces.ts
  app/src/app/shared/models/models.ts
  app/src/app/shared/models/utils.ts
Labels: frontend

#52 refactored environments and added checks for all app-information comp…
  app/src/app/core/components/analytics/analytics.component.ts
  app/src/app/core/services/ddk.service.ts
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/core/services/iconclass/iconclass.service.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/location/location.component.html
  app/src/app/pages/material/material.component.html
  app/src/app/pages/type/type.component.html
  app/src/app/shared/components/iconclass/iconclass.component.html
  app/src/app/shared/components/iconclass/iconclass.component.scss
  app/src/app/shared/components/iconclass/iconclass.component.spec.ts
  app/src/app/shared/components/iconclass/iconclass.component.ts
  app/src/app/shared/components/information/information.component.html
  app/src/app/shared/components/information/information.component.ts
  app/src/app/shared/models/artwork.interface.ts
  app/src/app/shared/shared.module.ts
  app/src/environments/environment.docker.ts
  app/src/environments/environment.prod.ts
  app/src/environments/environment.ts
  app/src/environments/environment_elastic.local.ts
  app/src/environments/environment_elastic.ts
Labels: frontend, medium priority
