Repository hochschule-darmstadt-UAS/ddk-artbrowser, pull requests merged in 2021-01, with the labels that each got.

#53 14/modifications to image fullscreen mode
  app/src/app/core/components/footer/footer.component.html
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.scss
  app/src/app/pages/artwork/artwork.component.ts
Labels: frontend

#54 13/iconclass show hierarchical related child artworks
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/core/services/iconclass/iconclass.service.ts
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/iconography/iconography.component.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
Labels: frontend, medium priority

#68 add iconography tile to home page
  app/src/app/app.routing.module.ts
  app/src/app/core/components/header/header.component.html
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/entities/entities.component.ts
  app/src/app/pages/home/home.component.html
  app/src/app/pages/home/home.component.ts
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/shared/components/collapse/collapse.component.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
Labels: frontend, high priority

#69 59/colored background images on home page
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/home/home.component.ts
  app/src/config/home_content.json
  app/src/config/home_movements.json
  app/tsconfig.json
Labels: frontend, high priority

#71 56/revise and translate static component texts
  app/src/app/pages/about/about.component.html
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/data-protection/data-protection.component.html
  app/src/app/pages/imprint/imprint.component.html
  app/src/styles/styles.scss
Labels: frontend, medium priority

#70 3/first xml importer
  .gitignore
  etl/.gitignore
  etl/Dockerfile
  etl/data_enhancement/README.md
  etl/data_enhancement/add_youtube_videos.py
  etl/data_enhancement/estimate_movement_period.py
  etl/data_enhancement/has_part_part_of_enhancement.py
  etl/data_enhancement/ranking.py
  etl/data_enhancement/split_languages.py
  etl/data_enhancement/youtube_videos.csv
  etl/data_extraction/README.md
  etl/data_extraction/__init__.py
  etl/data_extraction/artwork_ids_query.sparql
  etl/data_extraction/constants.py
  etl/data_extraction/get_wikidata_items.py
  etl/data_extraction/get_wikipedia_extracts.py
  etl/data_extraction/load_wd_entities.py
  etl/data_extraction/map_wd_attribute.py
  etl/data_extraction/map_wd_response.py
  etl/data_extraction/request_utils.py
  etl/data_samples/artwork.json
  etl/data_samples/iconography.json
  etl/etl-setup.sh
  etl/etl.sh
  etl/generate_rdf/art_ontology_header.txt
  etl/generate_rdf/generate_rdf.py
  etl/requirements.txt
  etl/scripts/data_extraction_statistics.sh
  etl/scripts/etl.sh
  etl/scripts/install_etl.bat
  etl/scripts/install_etl.sh
  etl/scripts/run_etl.bat
  etl/scripts/run_etl.sh
  etl/scripts/run_update_production.sh
  etl/scripts/update_elasticsearch_production_from_staging.sh
  etl/shared/__init__.py
  etl/shared/constants.py
  etl/shared/languageconfig.csv
  etl/shared/utils.py
  etl/upload_to_elasticsearch/elasticsearch_helper.py
  etl/upload_to_elasticsearch/elasticsearch_uploader.py
  etl/user-config.py
  etl/xml_importer/encoding.py
  etl/xml_importer/entities/artist.py
  etl/xml_importer/entities/artwork.py
  etl/xml_importer/entities/genre.py
  etl/xml_importer/entities/iconography.py
  etl/xml_importer/entities/location.py
  etl/xml_importer/entities/material.py
  etl/xml_importer/entities/type.py
  etl/xml_importer/main.py
  etl/xml_importer/merged.xml
  etl/xml_importer/parseLido.py
  etl/xml_importer/utils/entity.py
  etl/xml_importer/utils/measurement.py
  etl/xml_importer/utils/recordLegal.py
  etl/xml_importer/utils/resource.py
  etl/xml_importer/utils/rights.py
  etl/xml_importer/utils/sourceId.py
  etl/xml_importer/xpaths.py
Labels: backend, high priority

#91 Hotfix/0.1.1
  .github/workflows/deploy_staging.yml
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/entities/entities.component.ts
  app/src/app/pages/home/home.component.ts
  app/src/app/shared/components/search/search.component.ts
Labels: frontend, high priority

#96 66/error message for wrong ids and error page for 404
  app/src/app/app.routing.module.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.spec.ts
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/error/error.component.html
  app/src/app/pages/error/error.component.scss
  app/src/app/pages/error/error.component.spec.ts
  app/src/app/pages/error/error.component.ts
  app/src/app/pages/error/error.routing.module.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/genre/genre.component.spec.ts
  app/src/app/pages/genre/genre.component.ts
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/iconography/iconography.component.spec.ts
  app/src/app/pages/iconography/iconography.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/location/location.component.spec.ts
  app/src/app/pages/location/location.component.ts
  app/src/app/pages/material/material.component.html
  app/src/app/pages/material/material.component.spec.ts
  app/src/app/pages/material/material.component.ts
  app/src/app/pages/type/type.component.html
  app/src/app/pages/type/type.component.spec.ts
  app/src/app/pages/type/type.component.ts
  app/src/app/shared/components/wrong-id/wrong-id.component.html
  app/src/app/shared/components/wrong-id/wrong-id.component.scss
  app/src/app/shared/components/wrong-id/wrong-id.component.spec.ts
  app/src/app/shared/components/wrong-id/wrong-id.component.ts
  app/src/app/shared/shared.module.ts
  app/src/locale/messages.de.xlf
Labels: frontend, medium priority

#93 Hotfix/0.1.2
  app/src/app/app.routing.module.ts
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.spec.ts
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/entities/entities.component.scss
  app/src/app/pages/entities/entities.component.ts
  app/src/app/pages/error/error.component.html
  app/src/app/pages/error/error.component.scss
  app/src/app/pages/error/error.component.spec.ts
  app/src/app/pages/error/error.component.ts
  app/src/app/pages/error/error.routing.module.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/genre/genre.component.spec.ts
  app/src/app/pages/genre/genre.component.ts
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/iconography/iconography.component.spec.ts
  app/src/app/pages/iconography/iconography.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/location/location.component.spec.ts
  app/src/app/pages/location/location.component.ts
  app/src/app/pages/material/material.component.html
  app/src/app/pages/material/material.component.spec.ts
  app/src/app/pages/material/material.component.ts
  app/src/app/pages/type/type.component.html
  app/src/app/pages/type/type.component.spec.ts
  app/src/app/pages/type/type.component.ts
  app/src/app/shared/components/carousel/slide/slide.component.html
  app/src/app/shared/components/carousel/slide/slide.component.ts
  app/src/app/shared/components/search/search.component.ts
  app/src/app/shared/components/wrong-id/wrong-id.component.html
  app/src/app/shared/components/wrong-id/wrong-id.component.scss
  app/src/app/shared/components/wrong-id/wrong-id.component.spec.ts
  app/src/app/shared/components/wrong-id/wrong-id.component.ts
  app/src/app/shared/models/inlineInterfaces.ts
  app/src/app/shared/shared.module.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  etl/xml_importer/entities/location.py
Labels: frontend

#94 Fix the artwork and entity ranking
  etl/xml_importer/main.py
Labels: backend, bug

#97 Deploy Release 0.1.2
  app/src/app/app.routing.module.ts
  app/src/app/core/services/elasticsearch/data.service.ts
  app/src/app/pages/artist/artist.component.html
  app/src/app/pages/artist/artist.component.spec.ts
  app/src/app/pages/artist/artist.component.ts
  app/src/app/pages/artwork/artwork.component.html
  app/src/app/pages/artwork/artwork.component.spec.ts
  app/src/app/pages/artwork/artwork.component.ts
  app/src/app/pages/entities/entities.component.html
  app/src/app/pages/entities/entities.component.scss
  app/src/app/pages/entities/entities.component.ts
  app/src/app/pages/error/error.component.html
  app/src/app/pages/error/error.component.scss
  app/src/app/pages/error/error.component.spec.ts
  app/src/app/pages/error/error.component.ts
  app/src/app/pages/error/error.routing.module.ts
  app/src/app/pages/genre/genre.component.html
  app/src/app/pages/genre/genre.component.spec.ts
  app/src/app/pages/genre/genre.component.ts
  app/src/app/pages/iconography/iconography.component.html
  app/src/app/pages/iconography/iconography.component.spec.ts
  app/src/app/pages/iconography/iconography.component.ts
  app/src/app/pages/location/location.component.html
  app/src/app/pages/location/location.component.spec.ts
  app/src/app/pages/location/location.component.ts
  app/src/app/pages/material/material.component.html
  app/src/app/pages/material/material.component.spec.ts
  app/src/app/pages/material/material.component.ts
  app/src/app/pages/type/type.component.html
  app/src/app/pages/type/type.component.spec.ts
  app/src/app/pages/type/type.component.ts
  app/src/app/shared/components/carousel/slide/slide.component.html
  app/src/app/shared/components/carousel/slide/slide.component.ts
  app/src/app/shared/components/search/search.component.ts
  app/src/app/shared/components/wrong-id/wrong-id.component.html
  app/src/app/shared/components/wrong-id/wrong-id.component.scss
  app/src/app/shared/components/wrong-id/wrong-id.component.spec.ts
  app/src/app/shared/components/wrong-id/wrong-id.component.ts
  app/src/app/shared/models/inlineInterfaces.ts
  app/src/app/shared/shared.module.ts
  app/src/locale/messages.de.xlf
  app/src/locale/messages.en.xlf
  etl/xml_importer/entities/location.py
  etl/xml_importer/main.py
Labels: backend, frontend

#98 Location Hotfix and new Version Number
  app/package.json
  etl/xml_importer/entities/location.py
Labels: backend, frontend
